### ISSUE TITLE
Doesn't compile with petsc-3.9.1. Include files missing

### ISSUE THREAD

**Issue by fitz-culham** [wenjundeng/pic1dp#1]
Will try with 3.5 next

**Comment by fitz-culham** [comment]
` ../src/wtimer.F90:54:0: fatal error: finclude/petsc.h90: No such file or directory`

**Comment by hattom** [comment]
I haven't compiled it since petsc-3.5.3, but in principle (looking at an installation of petsc-3.8.3), the necessary file to #include is ROOT/include/petsc/finclude/petsc.h, as seen from ROOT as the installation of petsc (which depending on installer may be PETSC_DIR, PETSC_HOME, both or neither).

And of course check that the "include {...}/conf/variables" line in the makefile is able to find the variables file, which (in 3.8.3) appears to be in ROOT/lib/petsc/conf/variables [in 3.5.3 it was in ROOT/conf/variables].

**Comment by fitz-culham** [comment]
Thanks for the fast reply, looks like a nice code !

There are other files that no longer exist (I think petscdef, and some other files .h90). Some look to have been renamed not just moved.

**Comment by fitz-culham** [comment]
3.5.3 is fine thanks
